### ISSUE TITLE
Generated doc for built-in is empty (moved from GAMA)

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#13]
See discussion at https://github.com/gama-platform/gama/issues/1562

**Comment by mazarsju** [comment]
This issue is a bit old, and it causes a big "hole" in the current documentation... Is there anyone ready to handle this task ? @AlexisDrogoul @benoitgaudou ?

**Comment by mazarsju** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/8
