### ISSUE TITLE
Address of GAMA Google Group not easy to find on GitHub wiki

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#14]
Hi,

The address of the GAMA Google Group (https://groups.google.com/forum/#!forum/gama-platform) should be accessible easily from the main page of the GitHub wiki. For the moment, it is hidden behind the phrase `share it to its active community` (https://github.com/gama-platform/gama/wiki#multiple-application-domains) with no mention whatsoever of its interest in asking questions/receiving answers

**Comment by mazarsju** [comment]
The link to Google Group is easy to find from the website (under "Community / User forum"). I think we can close this issue then...
