### ISSUE TITLE
operators with 2 operands appears as "type OP type" instead of "OP(type,type)"

### ISSUE THREAD

**Issue by mazarsju** [mazarsju/gama_doc_17#23]
For some operators, it makes more sense to write the signature this way "OP(type,type)".

**Comment by mazarsju** [comment]
All the operators with 2 operands can be written "OP(type,type)" or "type OP type". I changed the documentation to put both possibilities.

**Comment by AlexisDrogoul** [comment]
It should be noted, also, that all the operators (with 3, 4, ... n operands) can be written with the first operand on the left.
