### ISSUE TITLE
Document how to have models in plugin library

### ISSUE THREAD

**Issue by agrignard** [mazarsju/gama_doc_17#25]
In this section https://github.com/gama-platform/gama/wiki/DevelopingPlugins 

we could have something like:

"
If you want to put model that illustrates the usage of your plugin do:
1. Create a folder called models/name_of_the_plugin
2. don't forget to have a .project
3. check unpack in feature.xml
   "

**Comment by mazarsju** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/12
