### ISSUE TITLE
Various UI problems

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#32]
Some problems I see
- The menu takes too much screen estate. Having a less wider one would be better.
- There is something I feel odd about the three tabs. They are "detached" and floating as if they were here by random. They are also too big. Maybe having simple radio buttons would be better (with a different background color for the menu ?). 
- The blue bar underneath the tabs is too prominent. Regarding previous comment, maybe having a left column for the menu with a background color depending on the tab (or button) chosen would simplify this design. The background colors could be pale variations of the three "GAMA colors" and the tabs could become icons with this color.
- The "close" icon is also really odd. It's difficult to understand its meaning. 
- The links are way too pale and it's difficult to read them. Using the blue of GAMA could be a possibility.

![gama2](https://cloud.githubusercontent.com/assets/579256/15446139/3266efcc-1f3f-11e6-8dcc-2e82da3324c9.png)

**Comment by mazarsju** [comment]
This issue is highly related with #38. I close it then.
