### ISSUE TITLE
Reorganize the structure of the website

### ISSUE THREAD

**Issue by mazarsju** [mazarsju/gama_doc_17#40]
Several points are to improve / change : 
- Change "References" into "Documentation"
- Add a "Features" part
- Reorganize the order of parts : "Features", "Download", "Tutorials", "Documentation", "Community" makes more sense.
- Add a page for each parts ( "Documentation", "Features" etc...) when clicking in the button, and respect a layout a bit like it is in the blender website : https://www.blender.org/features/. Here is an example of what it can be for the "Documentation" page : 

![image2](https://cloud.githubusercontent.com/assets/12977635/15452370/540f5456-2017-11e6-883c-da76c9ffdeab.png)

**Comment by mazarsju** [comment]
Here is an example of what the "feature" page could look like. 
nb : unlike the example provided for the "documentation" part, the titles are displayed in black, which means there are no "sub-section" for the different topics
nb2 : some "features" are not really "features", like "multiple application domains".
nb3 : this list is not exhaustive, we can add others (like "Interactive console", or "Serialize agents")

![image2](https://cloud.githubusercontent.com/assets/12977635/15671958/d4b8421a-2757-11e6-836f-93d2290b1ada.png)

**Comment by sriramab** [comment]
You could say : examples from multiple domains; which means GAMA features model files with examples from multiple domains.... so may be needs just a bit of rewording.

**Comment by mazarsju** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/14
