### ISSUE TITLE
Headings of the left menu

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#42]
Several small things:
- they should be opened automatically at the corresponding page/section
- I'm less and less excited by these big orange blobs. Maybe an orange text would be enough
- It is strange to put the Models Library first
- Adopting "User Guide" for "Platform Documentation" could probably mean more things to a beginner
- Adopting "Modeler Guide" instead of "References" also.
- The list of plugins should be updated to reflect the ones actually found in the gama repository.

![gama6](https://cloud.githubusercontent.com/assets/579256/15453556/9accb3de-2044-11e6-93da-bb8667a176c3.png)

**Comment by mazarsju** [comment]
Tastes and colors :) I personally like it better with the "big orange blobs". And it can allow the user to expand / collapse the parts easily.

![image3 2](https://cloud.githubusercontent.com/assets/12977635/15453700/9358b1ac-2049-11e6-8de4-481ca8109395.png)

A have nothing against changing the names of the different parts as you mention.

I had the same remark about the position of "model library" indeed : it is strange to put it in first position.

**Comment by sriramab** [comment]
I think there is also something mischievous about the left menu as we discussed. It does not respect the boundaries of the banners. See image for example, the menu overflows the bottom banner. I am also against the orange blogs. It might be simpler to consider what are known as frames, and have filled frames with orange colour. they are lighter and smoother to load.

![gama is a modeling and simulation development environment for building spatially explicit agent-based simulations 2016-05-23](https://cloud.githubusercontent.com/assets/12668606/15464987/61acab96-20fc-11e6-995f-3a0d94a9d166.png)

Here is another simple interface btw, not very beautiful but clear in message.
http://www.matsim.org/docs

**Comment by mazarsju** [comment]
Moved to https://github.com/gama-platform/gama.doc/issues/16
