### ISSUE TITLE
Troubleshooting/Installation link on download page

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#44]
The download page should have a direct link to the sections dedicated to Installation/Troubleshooting pages in the doc.

**Comment by mazarsju** [comment]
I added also a link to the corresponding pdf.

**Comment by mazarsju** [comment]
Finally I changed the two links "installation" and "troubleshooting" to the "get started" section, and I added the link to "troubleshooting" in the "get started" section.
