### ISSUE TITLE
website search down?

### ISSUE THREAD

**Issue by sriramab** [mazarsju/gama_doc_17#48]
Hi 

I was trying to use search on the new website, it gives the suggestions but clicking on the suggestions does not open anything. Is the website working?

Srirama

**Comment by mazarsju** [comment]
Hi Srirama,

Yes, I don't know what is happening with the search engine since yesterday it's down... I asked the webdeveloper to investigate, I hope it will be fixed soon, sorry about that...

**Comment by sriramab** [comment]
Still doesn't work for me :-(

**Comment by mazarsju** [comment]
Mmm... That's weird. It works fine for me on chrome and mozilla... Maybe a problem of Safari then... Is it also the case for other users of Safari ? ( @AlexisDrogoul  ? )

**Comment by sriramab** [comment]
Worked after a recent apple safari update and also I upgraded java on my machine. Not sure which one is related.
