### ISSUE TITLE
Downloads page broken

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#49]
Hi

The download page for gama 1.7 
http://51.255.46.42/releases/gama1_7_b1_OSX.exe

doesn't work
(moved from https://github.com/gama-platform/gama/issues/1908)

**Comment by mazarsju** [comment]
Something has been changed about the links (https://github.com/gama-platform/gama/wiki/Download) right @AlexisDrogoul ? What are the links for the 1.7 b1 now ?

**Comment by mazarsju** [comment]
Something has been changed about the links (https://github.com/gama-platform/gama/wiki/Download) right @AlexisDrogoul ? What are the links for the 1.7 b1 now ?

**Comment by AlexisDrogoul** [comment]
No idea. I can however create a release so we can point to this one. That would be the best solution, I guess.

**Comment by mazarsju** [comment]
Only the sources are available for the version you just created, I don't have the built (https://github.com/gama-platform/gama/releases/tag/v1.7)

**Comment by AlexisDrogoul** [comment]
Coming... However, they have to be tested beforehand so that we're sure we do not release a buggy version...

**Comment by AlexisDrogoul** [comment]
Done at last. You can now repair the links by using the ones provided on the "release" page.

**Comment by mazarsju** [comment]
I just corrected this. Now 3 downloads are available : 
- Gama Latest Builds (with a link to the continuous builds page)
- Gama 1.7 (the latest stable official version)
- Gama 1.6.1
  Gama 1.6 has been removed.
