### ISSUE TITLE
Moving the doc repository + issue list to gama GitHub site

### ISSUE THREAD

**Issue by AlexisDrogoul** [mazarsju/gama_doc_17#50]
A number of people (esp. users) are unaware of the existence of this issue list. We should probably move it to the "official" gama-platform organization (creating a "gama.doc" repository for the occasion). Since there is currently nothing in the repository here, maybe it could be the occasion to move the pages of the official site there (I dont know how / where they are maintained) ? Or to link the issue site with the repository of wiki pages ?

**Comment by mazarsju** [comment]
Yes sure, I 100% agree on this. I can handle this task if you want.

**Comment by mazarsju** [comment]
Done
